version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://mydb_d71p_user:mU4u5tHPjKGKHqGjONALS8fSBXXbcecH@dpg-csbi033tq21c73a0pq60-a.oregon-postgres.render.com/mydb_d71p  
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: mydb_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
